name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install astyle
        run: sudo apt-get -y install astyle

      - name: Check code style
        run: |
          (cd Software/ && astyle -n -r --options=codestyle.conf '*.ino' '*.cpp' '*.h')
          git diff --exit-code
